### ISSUE TITLE
For some reason I cant install noise from  pip install noise

### ISSUE THREAD

**Issue by Aarekaz** [johnafish/sketchbook#1]
It throws this error when I try to run sktechbook.py 
![image](https://user-images.githubusercontent.com/36888347/84585201-f62a9000-ae2c-11ea-96e2-cf2afefeb86a.png)
and when I try to install noise it throws a error 
![image](https://user-images.githubusercontent.com/36888347/84585343-ca100e80-ae2e-11ea-8a61-c71e799fa269.png)

Any Idea whats happening?

**Comment by HarshitRuwali** [comment]
There is no error in noise package. I just installed and it worked fine for me.
<img width="608" alt="Screenshot 2020-06-14 at 11 12 34 AM" src="https://user-images.githubusercontent.com/53895966/84585692-f4160080-ae2f-11ea-938f-2d2e3af99f00.png">
This might be because of the errors in wheel (a package which comes by default when you install python). 
Try reinstalling the wheel package, by
`pip uninstall wheel`
then
`pip install wheel`
Then try again installing noise. 
Hope this helps.

**Comment by Aarekaz** [comment]
![image](https://user-images.githubusercontent.com/36888347/84585746-98994200-ae32-11ea-813f-54d456e40824.png)
This is what happens when I try to install it

**Comment by HarshitRuwali** [comment]
Then this is because, you don't have C++ installed, follow the link and that should help.

**Comment by Aarekaz** [comment]
It worked
Thank you
